"""
Core Data Structure - MemoryEntry (Atomic Entry)

Paper Reference: Section 3.1 - Atomic Entries {m_k}
Each MemoryEntry represents a self-contained, disambiguated fact extracted
from dialogue via the De-linearization transformation F_θ
"""
from typing import List, Optional
from pydantic import BaseModel, Field, model_validator
import uuid
import hashlib


def _generate_content_hash(lossless_restatement: str, agent_id: str = None, user_id: str = None, user_name: str = None) -> str:
    """
    Generate deterministic entry_id from content hash.
    Same content + agent + user = same entry_id for deduplication.
    Note: user_name is NOT included in hash - only user_id matters for isolation.
    """
    content = f"{lossless_restatement}|{agent_id or ''}|{user_id or ''}"
    return hashlib.sha256(content.encode('utf-8')).hexdigest()[:32]


class MemoryEntry(BaseModel):
    """
    Atomic Entry - Self-contained memory unit indexed across three orthogonal layers

    Paper Reference: Section 3.1 - Eq. (3), (4)
    Generated by De-linearization: m_k = F_θ(W_t) = Φ_time ∘ Φ_coref ∘ Φ_extract(W_t)
    Indexed via: M(m_k) = {v_k (semantic), h_k (lexical), R_k (symbolic)}
    
    entry_id is auto-generated from content hash for deduplication:
    - Same lossless_restatement + agent_id + user_id = same entry_id
    - PgVectorStore uses ON CONFLICT to update instead of duplicate
    """
    entry_id: Optional[str] = Field(
        default=None,
        description="Auto-generated from content hash for deduplication"
    )

    # [Semantic Layer] - Dense embedding base (v_k = E_dense(S_k))
    lossless_restatement: str = Field(
        ...,
        description="Self-contained fact with Φ_coref (no pronouns) and Φ_time (absolute timestamps)"
    )

    # [Lexical Layer] - Sparse keyword vectors (h_k = Sparse(S_k))
    keywords: List[str] = Field(
        default_factory=list,
        description="Core keywords for BM25-style exact matching"
    )

    # [Symbolic Layer] - Metadata constraints (R_k = {(key, val)})
    timestamp: Optional[str] = Field(
        None,
        description="Standardized time in ISO 8601 format (YYYY-MM-DDTHH:MM:SS)"
    )
    location: Optional[str] = Field(
        None,
        description="Natural language location description"
    )
    persons: List[str] = Field(
        default_factory=list,
        description="List of extracted persons"
    )
    entities: List[str] = Field(
        default_factory=list,
        description="List of extracted entities (companies, products, etc.)"
    )
    topic: Optional[str] = Field(
        None,
        description="Topic phrase summarized by LLM"
    )
    
    # Memory classification for Ranger context
    memory_type: Optional[str] = Field(
        None,
        description="Type: 'correction' (user corrected), 'feedback' (explicit rating), 'pattern' (tool failure/success), 'preference' (user preference)"
    )
    scope: Optional[str] = Field(
        None,
        description="Scope: 'entity' (specific to one entity), 'universal' (applies broadly)"
    )
    source_entity: Optional[str] = Field(
        None,
        description="For patterns, the entity this insight was derived from (provenance)"
    )
    confidence: Optional[float] = Field(
        None,
        description="Confidence score: 1.0 for user corrections, 0.8 for tool results, 0.6 for patterns"
    )
    
    # Multi-tenant fields for agent/user isolation
    agent_id: Optional[str] = Field(
        None,
        description="Agent identifier for multi-agent isolation"
    )
    user_id: Optional[str] = Field(
        None,
        description="User identifier for multi-user isolation"
    )
    user_name: Optional[str] = Field(
        None,
        description="Human-readable user name for display purposes"
    )
    
    # Database timestamp (when entry was created)
    created_at: Optional[str] = Field(
        None,
        description="ISO 8601 timestamp of when the memory was stored in the database"
    )

    @model_validator(mode='after')
    def generate_entry_id(self):
        """Generate content-based entry_id for deduplication if not provided."""
        if not self.entry_id:
            self.entry_id = _generate_content_hash(
                self.lossless_restatement, 
                self.agent_id, 
                self.user_id
            )
        return self

    class Config:
        json_schema_extra = {
            "example": {
                "entry_id": "550e8400-e29b-41d4-a716-446655440000",
                "lossless_restatement": "Alice discussed the marketing strategy for new product XYZ with Bob at Starbucks in Shanghai on November 15, 2025 at 14:30.",
                "keywords": ["Alice", "Bob", "product XYZ", "marketing strategy", "discussion"],
                "timestamp": "2025-11-15T14:30:00",
                "location": "Starbucks, Shanghai",
                "persons": ["Alice", "Bob"],
                "entities": ["product XYZ"],
                "topic": "Product marketing strategy discussion"
            }
        }


class Dialogue(BaseModel):
    """
    Original dialogue entry
    """
    dialogue_id: int
    speaker: str
    content: str
    timestamp: Optional[str] = None  # ISO 8601 format

    def __str__(self) -> str:
        time_str = f"[{self.timestamp}] " if self.timestamp else ""
        return f"{time_str}{self.speaker}: {self.content}"
